// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeGyroscopeProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeGyroscopeProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeGyroscope_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeGyroscope_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeGyroscopeProto_2eproto() {
  protobuf_AddDesc_CarlifeGyroscopeProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeGyroscopeProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeGyroscope_descriptor_ = file->message_type(0);
  static const int CarlifeGyroscope_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeGyroscope, samplescount_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeGyroscope, xaxisgyrosum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeGyroscope, yaxisgyrosum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeGyroscope, zaxisgyrosum_),
  };
  CarlifeGyroscope_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeGyroscope_descriptor_,
      CarlifeGyroscope::default_instance_,
      CarlifeGyroscope_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeGyroscope, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeGyroscope, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeGyroscope));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeGyroscopeProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeGyroscope_descriptor_, &CarlifeGyroscope::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeGyroscopeProto_2eproto() {
  delete CarlifeGyroscope::default_instance_;
  delete CarlifeGyroscope_reflection_;
}

void protobuf_AddDesc_CarlifeGyroscopeProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033CarlifeGyroscopeProto.proto\022\032com.baidu"
    ".carlife.protobuf\"j\n\020CarlifeGyroscope\022\024\n"
    "\014samplesCount\030\001 \002(\005\022\024\n\014xAxisGyroSum\030\002 \002("
    "\005\022\024\n\014yAxisGyroSum\030\003 \002(\005\022\024\n\014zAxisGyroSum\030"
    "\004 \002(\005", 165);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeGyroscopeProto.proto", &protobuf_RegisterTypes);
  CarlifeGyroscope::default_instance_ = new CarlifeGyroscope();
  CarlifeGyroscope::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeGyroscopeProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeGyroscopeProto_2eproto {
  StaticDescriptorInitializer_CarlifeGyroscopeProto_2eproto() {
    protobuf_AddDesc_CarlifeGyroscopeProto_2eproto();
  }
} static_descriptor_initializer_CarlifeGyroscopeProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeGyroscope::kSamplesCountFieldNumber;
const int CarlifeGyroscope::kXAxisGyroSumFieldNumber;
const int CarlifeGyroscope::kYAxisGyroSumFieldNumber;
const int CarlifeGyroscope::kZAxisGyroSumFieldNumber;
#endif  // !_MSC_VER

CarlifeGyroscope::CarlifeGyroscope()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeGyroscope::InitAsDefaultInstance() {
}

CarlifeGyroscope::CarlifeGyroscope(const CarlifeGyroscope& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeGyroscope::SharedCtor() {
  _cached_size_ = 0;
  samplescount_ = 0;
  xaxisgyrosum_ = 0;
  yaxisgyrosum_ = 0;
  zaxisgyrosum_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeGyroscope::~CarlifeGyroscope() {
  SharedDtor();
}

void CarlifeGyroscope::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeGyroscope::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeGyroscope::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeGyroscope_descriptor_;
}

const CarlifeGyroscope& CarlifeGyroscope::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeGyroscopeProto_2eproto();
  return *default_instance_;
}

CarlifeGyroscope* CarlifeGyroscope::default_instance_ = NULL;

CarlifeGyroscope* CarlifeGyroscope::New() const {
  return new CarlifeGyroscope;
}

void CarlifeGyroscope::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    samplescount_ = 0;
    xaxisgyrosum_ = 0;
    yaxisgyrosum_ = 0;
    zaxisgyrosum_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeGyroscope::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 samplesCount = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &samplescount_)));
          set_has_samplescount();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_xAxisGyroSum;
        break;
      }

      // required int32 xAxisGyroSum = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_xAxisGyroSum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &xaxisgyrosum_)));
          set_has_xaxisgyrosum();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_yAxisGyroSum;
        break;
      }

      // required int32 yAxisGyroSum = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_yAxisGyroSum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &yaxisgyrosum_)));
          set_has_yaxisgyrosum();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_zAxisGyroSum;
        break;
      }

      // required int32 zAxisGyroSum = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_zAxisGyroSum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &zaxisgyrosum_)));
          set_has_zaxisgyrosum();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeGyroscope::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 samplesCount = 1;
  if (has_samplescount()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->samplescount(), output);
  }

  // required int32 xAxisGyroSum = 2;
  if (has_xaxisgyrosum()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->xaxisgyrosum(), output);
  }

  // required int32 yAxisGyroSum = 3;
  if (has_yaxisgyrosum()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->yaxisgyrosum(), output);
  }

  // required int32 zAxisGyroSum = 4;
  if (has_zaxisgyrosum()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->zaxisgyrosum(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeGyroscope::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 samplesCount = 1;
  if (has_samplescount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->samplescount(), target);
  }

  // required int32 xAxisGyroSum = 2;
  if (has_xaxisgyrosum()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->xaxisgyrosum(), target);
  }

  // required int32 yAxisGyroSum = 3;
  if (has_yaxisgyrosum()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->yaxisgyrosum(), target);
  }

  // required int32 zAxisGyroSum = 4;
  if (has_zaxisgyrosum()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->zaxisgyrosum(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeGyroscope::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 samplesCount = 1;
    if (has_samplescount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->samplescount());
    }

    // required int32 xAxisGyroSum = 2;
    if (has_xaxisgyrosum()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->xaxisgyrosum());
    }

    // required int32 yAxisGyroSum = 3;
    if (has_yaxisgyrosum()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->yaxisgyrosum());
    }

    // required int32 zAxisGyroSum = 4;
    if (has_zaxisgyrosum()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->zaxisgyrosum());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeGyroscope::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeGyroscope* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeGyroscope*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeGyroscope::MergeFrom(const CarlifeGyroscope& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_samplescount()) {
      set_samplescount(from.samplescount());
    }
    if (from.has_xaxisgyrosum()) {
      set_xaxisgyrosum(from.xaxisgyrosum());
    }
    if (from.has_yaxisgyrosum()) {
      set_yaxisgyrosum(from.yaxisgyrosum());
    }
    if (from.has_zaxisgyrosum()) {
      set_zaxisgyrosum(from.zaxisgyrosum());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeGyroscope::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeGyroscope::CopyFrom(const CarlifeGyroscope& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeGyroscope::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void CarlifeGyroscope::Swap(CarlifeGyroscope* other) {
  if (other != this) {
    std::swap(samplescount_, other->samplescount_);
    std::swap(xaxisgyrosum_, other->xaxisgyrosum_);
    std::swap(yaxisgyrosum_, other->yaxisgyrosum_);
    std::swap(zaxisgyrosum_, other->zaxisgyrosum_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeGyroscope::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeGyroscope_descriptor_;
  metadata.reflection = CarlifeGyroscope_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
