// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeTTSInitProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeTTSInitProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeTTSInit_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeTTSInit_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeTTSInitProto_2eproto() {
  protobuf_AddDesc_CarlifeTTSInitProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeTTSInitProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeTTSInit_descriptor_ = file->message_type(0);
  static const int CarlifeTTSInit_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeTTSInit, samplerate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeTTSInit, channelconfig_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeTTSInit, sampleformat_),
  };
  CarlifeTTSInit_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeTTSInit_descriptor_,
      CarlifeTTSInit::default_instance_,
      CarlifeTTSInit_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeTTSInit, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeTTSInit, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeTTSInit));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeTTSInitProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeTTSInit_descriptor_, &CarlifeTTSInit::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeTTSInitProto_2eproto() {
  delete CarlifeTTSInit::default_instance_;
  delete CarlifeTTSInit_reflection_;
}

void protobuf_AddDesc_CarlifeTTSInitProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031CarlifeTTSInitProto.proto\022\032com.baidu.c"
    "arlife.protobuf\"Q\n\016CarlifeTTSInit\022\022\n\nsam"
    "pleRate\030\001 \002(\005\022\025\n\rchannelConfig\030\002 \002(\005\022\024\n\014"
    "sampleFormat\030\003 \002(\005", 138);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeTTSInitProto.proto", &protobuf_RegisterTypes);
  CarlifeTTSInit::default_instance_ = new CarlifeTTSInit();
  CarlifeTTSInit::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeTTSInitProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeTTSInitProto_2eproto {
  StaticDescriptorInitializer_CarlifeTTSInitProto_2eproto() {
    protobuf_AddDesc_CarlifeTTSInitProto_2eproto();
  }
} static_descriptor_initializer_CarlifeTTSInitProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeTTSInit::kSampleRateFieldNumber;
const int CarlifeTTSInit::kChannelConfigFieldNumber;
const int CarlifeTTSInit::kSampleFormatFieldNumber;
#endif  // !_MSC_VER

CarlifeTTSInit::CarlifeTTSInit()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeTTSInit::InitAsDefaultInstance() {
}

CarlifeTTSInit::CarlifeTTSInit(const CarlifeTTSInit& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeTTSInit::SharedCtor() {
  _cached_size_ = 0;
  samplerate_ = 0;
  channelconfig_ = 0;
  sampleformat_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeTTSInit::~CarlifeTTSInit() {
  SharedDtor();
}

void CarlifeTTSInit::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeTTSInit::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeTTSInit::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeTTSInit_descriptor_;
}

const CarlifeTTSInit& CarlifeTTSInit::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeTTSInitProto_2eproto();
  return *default_instance_;
}

CarlifeTTSInit* CarlifeTTSInit::default_instance_ = NULL;

CarlifeTTSInit* CarlifeTTSInit::New() const {
  return new CarlifeTTSInit;
}

void CarlifeTTSInit::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    samplerate_ = 0;
    channelconfig_ = 0;
    sampleformat_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeTTSInit::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 sampleRate = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &samplerate_)));
          set_has_samplerate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_channelConfig;
        break;
      }

      // required int32 channelConfig = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_channelConfig:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &channelconfig_)));
          set_has_channelconfig();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_sampleFormat;
        break;
      }

      // required int32 sampleFormat = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_sampleFormat:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sampleformat_)));
          set_has_sampleformat();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeTTSInit::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 sampleRate = 1;
  if (has_samplerate()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->samplerate(), output);
  }

  // required int32 channelConfig = 2;
  if (has_channelconfig()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->channelconfig(), output);
  }

  // required int32 sampleFormat = 3;
  if (has_sampleformat()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->sampleformat(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeTTSInit::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 sampleRate = 1;
  if (has_samplerate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->samplerate(), target);
  }

  // required int32 channelConfig = 2;
  if (has_channelconfig()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->channelconfig(), target);
  }

  // required int32 sampleFormat = 3;
  if (has_sampleformat()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->sampleformat(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeTTSInit::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 sampleRate = 1;
    if (has_samplerate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->samplerate());
    }

    // required int32 channelConfig = 2;
    if (has_channelconfig()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->channelconfig());
    }

    // required int32 sampleFormat = 3;
    if (has_sampleformat()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->sampleformat());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeTTSInit::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeTTSInit* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeTTSInit*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeTTSInit::MergeFrom(const CarlifeTTSInit& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_samplerate()) {
      set_samplerate(from.samplerate());
    }
    if (from.has_channelconfig()) {
      set_channelconfig(from.channelconfig());
    }
    if (from.has_sampleformat()) {
      set_sampleformat(from.sampleformat());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeTTSInit::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeTTSInit::CopyFrom(const CarlifeTTSInit& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeTTSInit::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void CarlifeTTSInit::Swap(CarlifeTTSInit* other) {
  if (other != this) {
    std::swap(samplerate_, other->samplerate_);
    std::swap(channelconfig_, other->channelconfig_);
    std::swap(sampleformat_, other->sampleformat_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeTTSInit::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeTTSInit_descriptor_;
  metadata.reflection = CarlifeTTSInit_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
