// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeTouchSinglePointProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeTouchSinglePointProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeTouchSinglePoint_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeTouchSinglePoint_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeTouchSinglePointProto_2eproto() {
  protobuf_AddDesc_CarlifeTouchSinglePointProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeTouchSinglePointProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeTouchSinglePoint_descriptor_ = file->message_type(0);
  static const int CarlifeTouchSinglePoint_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeTouchSinglePoint, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeTouchSinglePoint, y_),
  };
  CarlifeTouchSinglePoint_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeTouchSinglePoint_descriptor_,
      CarlifeTouchSinglePoint::default_instance_,
      CarlifeTouchSinglePoint_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeTouchSinglePoint, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeTouchSinglePoint, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeTouchSinglePoint));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeTouchSinglePointProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeTouchSinglePoint_descriptor_, &CarlifeTouchSinglePoint::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeTouchSinglePointProto_2eproto() {
  delete CarlifeTouchSinglePoint::default_instance_;
  delete CarlifeTouchSinglePoint_reflection_;
}

void protobuf_AddDesc_CarlifeTouchSinglePointProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"CarlifeTouchSinglePointProto.proto\022\032co"
    "m.baidu.carlife.protobuf\"/\n\027CarlifeTouch"
    "SinglePoint\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005", 113);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeTouchSinglePointProto.proto", &protobuf_RegisterTypes);
  CarlifeTouchSinglePoint::default_instance_ = new CarlifeTouchSinglePoint();
  CarlifeTouchSinglePoint::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeTouchSinglePointProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeTouchSinglePointProto_2eproto {
  StaticDescriptorInitializer_CarlifeTouchSinglePointProto_2eproto() {
    protobuf_AddDesc_CarlifeTouchSinglePointProto_2eproto();
  }
} static_descriptor_initializer_CarlifeTouchSinglePointProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeTouchSinglePoint::kXFieldNumber;
const int CarlifeTouchSinglePoint::kYFieldNumber;
#endif  // !_MSC_VER

CarlifeTouchSinglePoint::CarlifeTouchSinglePoint()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeTouchSinglePoint::InitAsDefaultInstance() {
}

CarlifeTouchSinglePoint::CarlifeTouchSinglePoint(const CarlifeTouchSinglePoint& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeTouchSinglePoint::SharedCtor() {
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeTouchSinglePoint::~CarlifeTouchSinglePoint() {
  SharedDtor();
}

void CarlifeTouchSinglePoint::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeTouchSinglePoint::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeTouchSinglePoint::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeTouchSinglePoint_descriptor_;
}

const CarlifeTouchSinglePoint& CarlifeTouchSinglePoint::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeTouchSinglePointProto_2eproto();
  return *default_instance_;
}

CarlifeTouchSinglePoint* CarlifeTouchSinglePoint::default_instance_ = NULL;

CarlifeTouchSinglePoint* CarlifeTouchSinglePoint::New() const {
  return new CarlifeTouchSinglePoint;
}

void CarlifeTouchSinglePoint::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    x_ = 0;
    y_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeTouchSinglePoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 x = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_y;
        break;
      }

      // required int32 y = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeTouchSinglePoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 x = 1;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->x(), output);
  }

  // required int32 y = 2;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->y(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeTouchSinglePoint::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 x = 1;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->x(), target);
  }

  // required int32 y = 2;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->y(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeTouchSinglePoint::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 x = 1;
    if (has_x()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->x());
    }

    // required int32 y = 2;
    if (has_y()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->y());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeTouchSinglePoint::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeTouchSinglePoint* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeTouchSinglePoint*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeTouchSinglePoint::MergeFrom(const CarlifeTouchSinglePoint& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeTouchSinglePoint::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeTouchSinglePoint::CopyFrom(const CarlifeTouchSinglePoint& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeTouchSinglePoint::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void CarlifeTouchSinglePoint::Swap(CarlifeTouchSinglePoint* other) {
  if (other != this) {
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeTouchSinglePoint::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeTouchSinglePoint_descriptor_;
  metadata.reflection = CarlifeTouchSinglePoint_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
