// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeGearInfoProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeGearInfoProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeGearInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeGearInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeGearInfoProto_2eproto() {
  protobuf_AddDesc_CarlifeGearInfoProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeGearInfoProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeGearInfo_descriptor_ = file->message_type(0);
  static const int CarlifeGearInfo_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeGearInfo, gear_),
  };
  CarlifeGearInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeGearInfo_descriptor_,
      CarlifeGearInfo::default_instance_,
      CarlifeGearInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeGearInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeGearInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeGearInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeGearInfoProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeGearInfo_descriptor_, &CarlifeGearInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeGearInfoProto_2eproto() {
  delete CarlifeGearInfo::default_instance_;
  delete CarlifeGearInfo_reflection_;
}

void protobuf_AddDesc_CarlifeGearInfoProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032CarlifeGearInfoProto.proto\022\032com.baidu."
    "carlife.protobuf\"\037\n\017CarlifeGearInfo\022\014\n\004g"
    "ear\030\001 \002(\005", 89);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeGearInfoProto.proto", &protobuf_RegisterTypes);
  CarlifeGearInfo::default_instance_ = new CarlifeGearInfo();
  CarlifeGearInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeGearInfoProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeGearInfoProto_2eproto {
  StaticDescriptorInitializer_CarlifeGearInfoProto_2eproto() {
    protobuf_AddDesc_CarlifeGearInfoProto_2eproto();
  }
} static_descriptor_initializer_CarlifeGearInfoProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeGearInfo::kGearFieldNumber;
#endif  // !_MSC_VER

CarlifeGearInfo::CarlifeGearInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeGearInfo::InitAsDefaultInstance() {
}

CarlifeGearInfo::CarlifeGearInfo(const CarlifeGearInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeGearInfo::SharedCtor() {
  _cached_size_ = 0;
  gear_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeGearInfo::~CarlifeGearInfo() {
  SharedDtor();
}

void CarlifeGearInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeGearInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeGearInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeGearInfo_descriptor_;
}

const CarlifeGearInfo& CarlifeGearInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeGearInfoProto_2eproto();
  return *default_instance_;
}

CarlifeGearInfo* CarlifeGearInfo::default_instance_ = NULL;

CarlifeGearInfo* CarlifeGearInfo::New() const {
  return new CarlifeGearInfo;
}

void CarlifeGearInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    gear_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeGearInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 gear = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &gear_)));
          set_has_gear();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeGearInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 gear = 1;
  if (has_gear()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->gear(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeGearInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 gear = 1;
  if (has_gear()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->gear(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeGearInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 gear = 1;
    if (has_gear()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->gear());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeGearInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeGearInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeGearInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeGearInfo::MergeFrom(const CarlifeGearInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_gear()) {
      set_gear(from.gear());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeGearInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeGearInfo::CopyFrom(const CarlifeGearInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeGearInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CarlifeGearInfo::Swap(CarlifeGearInfo* other) {
  if (other != this) {
    std::swap(gear_, other->gear_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeGearInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeGearInfo_descriptor_;
  metadata.reflection = CarlifeGearInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
