// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeBTHfpStatusResponseProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeBTHfpStatusResponseProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeBTHfpStatusResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeBTHfpStatusResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeBTHfpStatusResponseProto_2eproto() {
  protobuf_AddDesc_CarlifeBTHfpStatusResponseProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeBTHfpStatusResponseProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeBTHfpStatusResponse_descriptor_ = file->message_type(0);
  static const int CarlifeBTHfpStatusResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeBTHfpStatusResponse, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeBTHfpStatusResponse, type_),
  };
  CarlifeBTHfpStatusResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeBTHfpStatusResponse_descriptor_,
      CarlifeBTHfpStatusResponse::default_instance_,
      CarlifeBTHfpStatusResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeBTHfpStatusResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeBTHfpStatusResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeBTHfpStatusResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeBTHfpStatusResponseProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeBTHfpStatusResponse_descriptor_, &CarlifeBTHfpStatusResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeBTHfpStatusResponseProto_2eproto() {
  delete CarlifeBTHfpStatusResponse::default_instance_;
  delete CarlifeBTHfpStatusResponse_reflection_;
}

void protobuf_AddDesc_CarlifeBTHfpStatusResponseProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n%CarlifeBTHfpStatusResponseProto.proto\022"
    "\032com.baidu.carlife.protobuf\":\n\032CarlifeBT"
    "HfpStatusResponse\022\016\n\006status\030\001 \002(\005\022\014\n\004typ"
    "e\030\002 \002(\005", 127);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeBTHfpStatusResponseProto.proto", &protobuf_RegisterTypes);
  CarlifeBTHfpStatusResponse::default_instance_ = new CarlifeBTHfpStatusResponse();
  CarlifeBTHfpStatusResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeBTHfpStatusResponseProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeBTHfpStatusResponseProto_2eproto {
  StaticDescriptorInitializer_CarlifeBTHfpStatusResponseProto_2eproto() {
    protobuf_AddDesc_CarlifeBTHfpStatusResponseProto_2eproto();
  }
} static_descriptor_initializer_CarlifeBTHfpStatusResponseProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeBTHfpStatusResponse::kStatusFieldNumber;
const int CarlifeBTHfpStatusResponse::kTypeFieldNumber;
#endif  // !_MSC_VER

CarlifeBTHfpStatusResponse::CarlifeBTHfpStatusResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeBTHfpStatusResponse::InitAsDefaultInstance() {
}

CarlifeBTHfpStatusResponse::CarlifeBTHfpStatusResponse(const CarlifeBTHfpStatusResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeBTHfpStatusResponse::SharedCtor() {
  _cached_size_ = 0;
  status_ = 0;
  type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeBTHfpStatusResponse::~CarlifeBTHfpStatusResponse() {
  SharedDtor();
}

void CarlifeBTHfpStatusResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeBTHfpStatusResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeBTHfpStatusResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeBTHfpStatusResponse_descriptor_;
}

const CarlifeBTHfpStatusResponse& CarlifeBTHfpStatusResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeBTHfpStatusResponseProto_2eproto();
  return *default_instance_;
}

CarlifeBTHfpStatusResponse* CarlifeBTHfpStatusResponse::default_instance_ = NULL;

CarlifeBTHfpStatusResponse* CarlifeBTHfpStatusResponse::New() const {
  return new CarlifeBTHfpStatusResponse;
}

void CarlifeBTHfpStatusResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    status_ = 0;
    type_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeBTHfpStatusResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 status = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
          set_has_status();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_type;
        break;
      }

      // required int32 type = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeBTHfpStatusResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 status = 1;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->status(), output);
  }

  // required int32 type = 2;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeBTHfpStatusResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 status = 1;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->status(), target);
  }

  // required int32 type = 2;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeBTHfpStatusResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 status = 1;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->status());
    }

    // required int32 type = 2;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeBTHfpStatusResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeBTHfpStatusResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeBTHfpStatusResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeBTHfpStatusResponse::MergeFrom(const CarlifeBTHfpStatusResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_status()) {
      set_status(from.status());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeBTHfpStatusResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeBTHfpStatusResponse::CopyFrom(const CarlifeBTHfpStatusResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeBTHfpStatusResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void CarlifeBTHfpStatusResponse::Swap(CarlifeBTHfpStatusResponse* other) {
  if (other != this) {
    std::swap(status_, other->status_);
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeBTHfpStatusResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeBTHfpStatusResponse_descriptor_;
  metadata.reflection = CarlifeBTHfpStatusResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
