// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeBTHfpStatusRequestProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeBTHfpStatusRequestProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeBTHfpStatusRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeBTHfpStatusRequest_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeBTHfpStatusRequestProto_2eproto() {
  protobuf_AddDesc_CarlifeBTHfpStatusRequestProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeBTHfpStatusRequestProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeBTHfpStatusRequest_descriptor_ = file->message_type(0);
  static const int CarlifeBTHfpStatusRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeBTHfpStatusRequest, type_),
  };
  CarlifeBTHfpStatusRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeBTHfpStatusRequest_descriptor_,
      CarlifeBTHfpStatusRequest::default_instance_,
      CarlifeBTHfpStatusRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeBTHfpStatusRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeBTHfpStatusRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeBTHfpStatusRequest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeBTHfpStatusRequestProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeBTHfpStatusRequest_descriptor_, &CarlifeBTHfpStatusRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeBTHfpStatusRequestProto_2eproto() {
  delete CarlifeBTHfpStatusRequest::default_instance_;
  delete CarlifeBTHfpStatusRequest_reflection_;
}

void protobuf_AddDesc_CarlifeBTHfpStatusRequestProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n$CarlifeBTHfpStatusRequestProto.proto\022\032"
    "com.baidu.carlife.protobuf\")\n\031CarlifeBTH"
    "fpStatusRequest\022\014\n\004type\030\001 \002(\005", 109);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeBTHfpStatusRequestProto.proto", &protobuf_RegisterTypes);
  CarlifeBTHfpStatusRequest::default_instance_ = new CarlifeBTHfpStatusRequest();
  CarlifeBTHfpStatusRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeBTHfpStatusRequestProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeBTHfpStatusRequestProto_2eproto {
  StaticDescriptorInitializer_CarlifeBTHfpStatusRequestProto_2eproto() {
    protobuf_AddDesc_CarlifeBTHfpStatusRequestProto_2eproto();
  }
} static_descriptor_initializer_CarlifeBTHfpStatusRequestProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeBTHfpStatusRequest::kTypeFieldNumber;
#endif  // !_MSC_VER

CarlifeBTHfpStatusRequest::CarlifeBTHfpStatusRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeBTHfpStatusRequest::InitAsDefaultInstance() {
}

CarlifeBTHfpStatusRequest::CarlifeBTHfpStatusRequest(const CarlifeBTHfpStatusRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeBTHfpStatusRequest::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeBTHfpStatusRequest::~CarlifeBTHfpStatusRequest() {
  SharedDtor();
}

void CarlifeBTHfpStatusRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeBTHfpStatusRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeBTHfpStatusRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeBTHfpStatusRequest_descriptor_;
}

const CarlifeBTHfpStatusRequest& CarlifeBTHfpStatusRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeBTHfpStatusRequestProto_2eproto();
  return *default_instance_;
}

CarlifeBTHfpStatusRequest* CarlifeBTHfpStatusRequest::default_instance_ = NULL;

CarlifeBTHfpStatusRequest* CarlifeBTHfpStatusRequest::New() const {
  return new CarlifeBTHfpStatusRequest;
}

void CarlifeBTHfpStatusRequest::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeBTHfpStatusRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeBTHfpStatusRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeBTHfpStatusRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeBTHfpStatusRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeBTHfpStatusRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeBTHfpStatusRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeBTHfpStatusRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeBTHfpStatusRequest::MergeFrom(const CarlifeBTHfpStatusRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeBTHfpStatusRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeBTHfpStatusRequest::CopyFrom(const CarlifeBTHfpStatusRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeBTHfpStatusRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CarlifeBTHfpStatusRequest::Swap(CarlifeBTHfpStatusRequest* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeBTHfpStatusRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeBTHfpStatusRequest_descriptor_;
  metadata.reflection = CarlifeBTHfpStatusRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
