// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeMediaProgressBarProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeMediaProgressBarProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeMediaProgressBar_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeMediaProgressBar_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeMediaProgressBarProto_2eproto() {
  protobuf_AddDesc_CarlifeMediaProgressBarProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeMediaProgressBarProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeMediaProgressBar_descriptor_ = file->message_type(0);
  static const int CarlifeMediaProgressBar_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeMediaProgressBar, progressbar_),
  };
  CarlifeMediaProgressBar_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeMediaProgressBar_descriptor_,
      CarlifeMediaProgressBar::default_instance_,
      CarlifeMediaProgressBar_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeMediaProgressBar, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeMediaProgressBar, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeMediaProgressBar));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeMediaProgressBarProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeMediaProgressBar_descriptor_, &CarlifeMediaProgressBar::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeMediaProgressBarProto_2eproto() {
  delete CarlifeMediaProgressBar::default_instance_;
  delete CarlifeMediaProgressBar_reflection_;
}

void protobuf_AddDesc_CarlifeMediaProgressBarProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"CarlifeMediaProgressBarProto.proto\022\032co"
    "m.baidu.carlife.protobuf\".\n\027CarlifeMedia"
    "ProgressBar\022\023\n\013progressBar\030\001 \002(\005", 112);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeMediaProgressBarProto.proto", &protobuf_RegisterTypes);
  CarlifeMediaProgressBar::default_instance_ = new CarlifeMediaProgressBar();
  CarlifeMediaProgressBar::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeMediaProgressBarProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeMediaProgressBarProto_2eproto {
  StaticDescriptorInitializer_CarlifeMediaProgressBarProto_2eproto() {
    protobuf_AddDesc_CarlifeMediaProgressBarProto_2eproto();
  }
} static_descriptor_initializer_CarlifeMediaProgressBarProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeMediaProgressBar::kProgressBarFieldNumber;
#endif  // !_MSC_VER

CarlifeMediaProgressBar::CarlifeMediaProgressBar()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeMediaProgressBar::InitAsDefaultInstance() {
}

CarlifeMediaProgressBar::CarlifeMediaProgressBar(const CarlifeMediaProgressBar& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeMediaProgressBar::SharedCtor() {
  _cached_size_ = 0;
  progressbar_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeMediaProgressBar::~CarlifeMediaProgressBar() {
  SharedDtor();
}

void CarlifeMediaProgressBar::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeMediaProgressBar::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeMediaProgressBar::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeMediaProgressBar_descriptor_;
}

const CarlifeMediaProgressBar& CarlifeMediaProgressBar::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeMediaProgressBarProto_2eproto();
  return *default_instance_;
}

CarlifeMediaProgressBar* CarlifeMediaProgressBar::default_instance_ = NULL;

CarlifeMediaProgressBar* CarlifeMediaProgressBar::New() const {
  return new CarlifeMediaProgressBar;
}

void CarlifeMediaProgressBar::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    progressbar_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeMediaProgressBar::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 progressBar = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &progressbar_)));
          set_has_progressbar();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeMediaProgressBar::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 progressBar = 1;
  if (has_progressbar()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->progressbar(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeMediaProgressBar::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 progressBar = 1;
  if (has_progressbar()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->progressbar(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeMediaProgressBar::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 progressBar = 1;
    if (has_progressbar()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->progressbar());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeMediaProgressBar::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeMediaProgressBar* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeMediaProgressBar*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeMediaProgressBar::MergeFrom(const CarlifeMediaProgressBar& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_progressbar()) {
      set_progressbar(from.progressbar());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeMediaProgressBar::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeMediaProgressBar::CopyFrom(const CarlifeMediaProgressBar& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeMediaProgressBar::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CarlifeMediaProgressBar::Swap(CarlifeMediaProgressBar* other) {
  if (other != this) {
    std::swap(progressbar_, other->progressbar_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeMediaProgressBar::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeMediaProgressBar_descriptor_;
  metadata.reflection = CarlifeMediaProgressBar_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
