// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeProtocolVersionProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeProtocolVersionProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeProtocolVersion_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeProtocolVersion_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeProtocolVersionProto_2eproto() {
  protobuf_AddDesc_CarlifeProtocolVersionProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeProtocolVersionProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeProtocolVersion_descriptor_ = file->message_type(0);
  static const int CarlifeProtocolVersion_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeProtocolVersion, majorversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeProtocolVersion, minorversion_),
  };
  CarlifeProtocolVersion_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeProtocolVersion_descriptor_,
      CarlifeProtocolVersion::default_instance_,
      CarlifeProtocolVersion_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeProtocolVersion, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeProtocolVersion, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeProtocolVersion));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeProtocolVersionProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeProtocolVersion_descriptor_, &CarlifeProtocolVersion::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeProtocolVersionProto_2eproto() {
  delete CarlifeProtocolVersion::default_instance_;
  delete CarlifeProtocolVersion_reflection_;
}

void protobuf_AddDesc_CarlifeProtocolVersionProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n!CarlifeProtocolVersionProto.proto\022\032com"
    ".baidu.carlife.protobuf\"D\n\026CarlifeProtoc"
    "olVersion\022\024\n\014majorVersion\030\001 \002(\005\022\024\n\014minor"
    "Version\030\002 \002(\005", 133);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeProtocolVersionProto.proto", &protobuf_RegisterTypes);
  CarlifeProtocolVersion::default_instance_ = new CarlifeProtocolVersion();
  CarlifeProtocolVersion::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeProtocolVersionProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeProtocolVersionProto_2eproto {
  StaticDescriptorInitializer_CarlifeProtocolVersionProto_2eproto() {
    protobuf_AddDesc_CarlifeProtocolVersionProto_2eproto();
  }
} static_descriptor_initializer_CarlifeProtocolVersionProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeProtocolVersion::kMajorVersionFieldNumber;
const int CarlifeProtocolVersion::kMinorVersionFieldNumber;
#endif  // !_MSC_VER

CarlifeProtocolVersion::CarlifeProtocolVersion()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeProtocolVersion::InitAsDefaultInstance() {
}

CarlifeProtocolVersion::CarlifeProtocolVersion(const CarlifeProtocolVersion& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeProtocolVersion::SharedCtor() {
  _cached_size_ = 0;
  majorversion_ = 0;
  minorversion_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeProtocolVersion::~CarlifeProtocolVersion() {
  SharedDtor();
}

void CarlifeProtocolVersion::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeProtocolVersion::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeProtocolVersion::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeProtocolVersion_descriptor_;
}

const CarlifeProtocolVersion& CarlifeProtocolVersion::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeProtocolVersionProto_2eproto();
  return *default_instance_;
}

CarlifeProtocolVersion* CarlifeProtocolVersion::default_instance_ = NULL;

CarlifeProtocolVersion* CarlifeProtocolVersion::New() const {
  return new CarlifeProtocolVersion;
}

void CarlifeProtocolVersion::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    majorversion_ = 0;
    minorversion_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeProtocolVersion::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 majorVersion = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &majorversion_)));
          set_has_majorversion();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_minorVersion;
        break;
      }

      // required int32 minorVersion = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_minorVersion:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &minorversion_)));
          set_has_minorversion();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeProtocolVersion::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 majorVersion = 1;
  if (has_majorversion()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->majorversion(), output);
  }

  // required int32 minorVersion = 2;
  if (has_minorversion()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->minorversion(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeProtocolVersion::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 majorVersion = 1;
  if (has_majorversion()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->majorversion(), target);
  }

  // required int32 minorVersion = 2;
  if (has_minorversion()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->minorversion(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeProtocolVersion::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 majorVersion = 1;
    if (has_majorversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->majorversion());
    }

    // required int32 minorVersion = 2;
    if (has_minorversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->minorversion());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeProtocolVersion::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeProtocolVersion* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeProtocolVersion*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeProtocolVersion::MergeFrom(const CarlifeProtocolVersion& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_majorversion()) {
      set_majorversion(from.majorversion());
    }
    if (from.has_minorversion()) {
      set_minorversion(from.minorversion());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeProtocolVersion::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeProtocolVersion::CopyFrom(const CarlifeProtocolVersion& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeProtocolVersion::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void CarlifeProtocolVersion::Swap(CarlifeProtocolVersion* other) {
  if (other != this) {
    std::swap(majorversion_, other->majorversion_);
    std::swap(minorversion_, other->minorversion_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeProtocolVersion::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeProtocolVersion_descriptor_;
  metadata.reflection = CarlifeProtocolVersion_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
