// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeCarSpeedProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeCarSpeedProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeCarSpeed_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeCarSpeed_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeCarSpeedProto_2eproto() {
  protobuf_AddDesc_CarlifeCarSpeedProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeCarSpeedProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeCarSpeed_descriptor_ = file->message_type(0);
  static const int CarlifeCarSpeed_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeCarSpeed, speed_),
  };
  CarlifeCarSpeed_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeCarSpeed_descriptor_,
      CarlifeCarSpeed::default_instance_,
      CarlifeCarSpeed_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeCarSpeed, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeCarSpeed, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeCarSpeed));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeCarSpeedProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeCarSpeed_descriptor_, &CarlifeCarSpeed::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeCarSpeedProto_2eproto() {
  delete CarlifeCarSpeed::default_instance_;
  delete CarlifeCarSpeed_reflection_;
}

void protobuf_AddDesc_CarlifeCarSpeedProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032CarlifeCarSpeedProto.proto\022\032com.baidu."
    "carlife.protobuf\" \n\017CarlifeCarSpeed\022\r\n\005s"
    "peed\030\001 \002(\005", 90);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeCarSpeedProto.proto", &protobuf_RegisterTypes);
  CarlifeCarSpeed::default_instance_ = new CarlifeCarSpeed();
  CarlifeCarSpeed::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeCarSpeedProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeCarSpeedProto_2eproto {
  StaticDescriptorInitializer_CarlifeCarSpeedProto_2eproto() {
    protobuf_AddDesc_CarlifeCarSpeedProto_2eproto();
  }
} static_descriptor_initializer_CarlifeCarSpeedProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeCarSpeed::kSpeedFieldNumber;
#endif  // !_MSC_VER

CarlifeCarSpeed::CarlifeCarSpeed()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeCarSpeed::InitAsDefaultInstance() {
}

CarlifeCarSpeed::CarlifeCarSpeed(const CarlifeCarSpeed& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeCarSpeed::SharedCtor() {
  _cached_size_ = 0;
  speed_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeCarSpeed::~CarlifeCarSpeed() {
  SharedDtor();
}

void CarlifeCarSpeed::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeCarSpeed::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeCarSpeed::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeCarSpeed_descriptor_;
}

const CarlifeCarSpeed& CarlifeCarSpeed::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeCarSpeedProto_2eproto();
  return *default_instance_;
}

CarlifeCarSpeed* CarlifeCarSpeed::default_instance_ = NULL;

CarlifeCarSpeed* CarlifeCarSpeed::New() const {
  return new CarlifeCarSpeed;
}

void CarlifeCarSpeed::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    speed_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeCarSpeed::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 speed = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &speed_)));
          set_has_speed();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeCarSpeed::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 speed = 1;
  if (has_speed()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->speed(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeCarSpeed::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 speed = 1;
  if (has_speed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->speed(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeCarSpeed::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 speed = 1;
    if (has_speed()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->speed());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeCarSpeed::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeCarSpeed* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeCarSpeed*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeCarSpeed::MergeFrom(const CarlifeCarSpeed& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_speed()) {
      set_speed(from.speed());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeCarSpeed::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeCarSpeed::CopyFrom(const CarlifeCarSpeed& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeCarSpeed::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CarlifeCarSpeed::Swap(CarlifeCarSpeed* other) {
  if (other != this) {
    std::swap(speed_, other->speed_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeCarSpeed::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeCarSpeed_descriptor_;
  metadata.reflection = CarlifeCarSpeed_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
