// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeVehicleInfoProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeVehicleInfoProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeVehicleInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeVehicleInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeVehicleInfoProto_2eproto() {
  protobuf_AddDesc_CarlifeVehicleInfoProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeVehicleInfoProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeVehicleInfo_descriptor_ = file->message_type(0);
  static const int CarlifeVehicleInfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVehicleInfo, moduleid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVehicleInfo, supportflag_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVehicleInfo, frequency_),
  };
  CarlifeVehicleInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeVehicleInfo_descriptor_,
      CarlifeVehicleInfo::default_instance_,
      CarlifeVehicleInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVehicleInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVehicleInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeVehicleInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeVehicleInfoProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeVehicleInfo_descriptor_, &CarlifeVehicleInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeVehicleInfoProto_2eproto() {
  delete CarlifeVehicleInfo::default_instance_;
  delete CarlifeVehicleInfo_reflection_;
}

void protobuf_AddDesc_CarlifeVehicleInfoProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035CarlifeVehicleInfoProto.proto\022\032com.bai"
    "du.carlife.protobuf\"N\n\022CarlifeVehicleInf"
    "o\022\020\n\010moduleID\030\001 \002(\005\022\023\n\013supportFlag\030\002 \001(\010"
    "\022\021\n\tfrequency\030\003 \001(\005", 139);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeVehicleInfoProto.proto", &protobuf_RegisterTypes);
  CarlifeVehicleInfo::default_instance_ = new CarlifeVehicleInfo();
  CarlifeVehicleInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeVehicleInfoProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeVehicleInfoProto_2eproto {
  StaticDescriptorInitializer_CarlifeVehicleInfoProto_2eproto() {
    protobuf_AddDesc_CarlifeVehicleInfoProto_2eproto();
  }
} static_descriptor_initializer_CarlifeVehicleInfoProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeVehicleInfo::kModuleIDFieldNumber;
const int CarlifeVehicleInfo::kSupportFlagFieldNumber;
const int CarlifeVehicleInfo::kFrequencyFieldNumber;
#endif  // !_MSC_VER

CarlifeVehicleInfo::CarlifeVehicleInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeVehicleInfo::InitAsDefaultInstance() {
}

CarlifeVehicleInfo::CarlifeVehicleInfo(const CarlifeVehicleInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeVehicleInfo::SharedCtor() {
  _cached_size_ = 0;
  moduleid_ = 0;
  supportflag_ = false;
  frequency_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeVehicleInfo::~CarlifeVehicleInfo() {
  SharedDtor();
}

void CarlifeVehicleInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeVehicleInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeVehicleInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeVehicleInfo_descriptor_;
}

const CarlifeVehicleInfo& CarlifeVehicleInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeVehicleInfoProto_2eproto();
  return *default_instance_;
}

CarlifeVehicleInfo* CarlifeVehicleInfo::default_instance_ = NULL;

CarlifeVehicleInfo* CarlifeVehicleInfo::New() const {
  return new CarlifeVehicleInfo;
}

void CarlifeVehicleInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    moduleid_ = 0;
    supportflag_ = false;
    frequency_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeVehicleInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 moduleID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &moduleid_)));
          set_has_moduleid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_supportFlag;
        break;
      }

      // optional bool supportFlag = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_supportFlag:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &supportflag_)));
          set_has_supportflag();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_frequency;
        break;
      }

      // optional int32 frequency = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_frequency:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &frequency_)));
          set_has_frequency();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeVehicleInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 moduleID = 1;
  if (has_moduleid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->moduleid(), output);
  }

  // optional bool supportFlag = 2;
  if (has_supportflag()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->supportflag(), output);
  }

  // optional int32 frequency = 3;
  if (has_frequency()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->frequency(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeVehicleInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 moduleID = 1;
  if (has_moduleid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->moduleid(), target);
  }

  // optional bool supportFlag = 2;
  if (has_supportflag()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->supportflag(), target);
  }

  // optional int32 frequency = 3;
  if (has_frequency()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->frequency(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeVehicleInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 moduleID = 1;
    if (has_moduleid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->moduleid());
    }

    // optional bool supportFlag = 2;
    if (has_supportflag()) {
      total_size += 1 + 1;
    }

    // optional int32 frequency = 3;
    if (has_frequency()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->frequency());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeVehicleInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeVehicleInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeVehicleInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeVehicleInfo::MergeFrom(const CarlifeVehicleInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_moduleid()) {
      set_moduleid(from.moduleid());
    }
    if (from.has_supportflag()) {
      set_supportflag(from.supportflag());
    }
    if (from.has_frequency()) {
      set_frequency(from.frequency());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeVehicleInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeVehicleInfo::CopyFrom(const CarlifeVehicleInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeVehicleInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CarlifeVehicleInfo::Swap(CarlifeVehicleInfo* other) {
  if (other != this) {
    std::swap(moduleid_, other->moduleid_);
    std::swap(supportflag_, other->supportflag_);
    std::swap(frequency_, other->frequency_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeVehicleInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeVehicleInfo_descriptor_;
  metadata.reflection = CarlifeVehicleInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
