// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeVideoEncoderInfoProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeVideoEncoderInfoProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeVideoEncoderInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeVideoEncoderInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeVideoEncoderInfoProto_2eproto() {
  protobuf_AddDesc_CarlifeVideoEncoderInfoProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeVideoEncoderInfoProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeVideoEncoderInfo_descriptor_ = file->message_type(0);
  static const int CarlifeVideoEncoderInfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVideoEncoderInfo, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVideoEncoderInfo, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVideoEncoderInfo, framerate_),
  };
  CarlifeVideoEncoderInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeVideoEncoderInfo_descriptor_,
      CarlifeVideoEncoderInfo::default_instance_,
      CarlifeVideoEncoderInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVideoEncoderInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeVideoEncoderInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeVideoEncoderInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeVideoEncoderInfoProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeVideoEncoderInfo_descriptor_, &CarlifeVideoEncoderInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeVideoEncoderInfoProto_2eproto() {
  delete CarlifeVideoEncoderInfo::default_instance_;
  delete CarlifeVideoEncoderInfo_reflection_;
}

void protobuf_AddDesc_CarlifeVideoEncoderInfoProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"CarlifeVideoEncoderInfoProto.proto\022\032co"
    "m.baidu.carlife.protobuf\"K\n\027CarlifeVideo"
    "EncoderInfo\022\r\n\005width\030\001 \002(\005\022\016\n\006height\030\002 \002"
    "(\005\022\021\n\tframeRate\030\003 \002(\005", 141);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeVideoEncoderInfoProto.proto", &protobuf_RegisterTypes);
  CarlifeVideoEncoderInfo::default_instance_ = new CarlifeVideoEncoderInfo();
  CarlifeVideoEncoderInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeVideoEncoderInfoProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeVideoEncoderInfoProto_2eproto {
  StaticDescriptorInitializer_CarlifeVideoEncoderInfoProto_2eproto() {
    protobuf_AddDesc_CarlifeVideoEncoderInfoProto_2eproto();
  }
} static_descriptor_initializer_CarlifeVideoEncoderInfoProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeVideoEncoderInfo::kWidthFieldNumber;
const int CarlifeVideoEncoderInfo::kHeightFieldNumber;
const int CarlifeVideoEncoderInfo::kFrameRateFieldNumber;
#endif  // !_MSC_VER

CarlifeVideoEncoderInfo::CarlifeVideoEncoderInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeVideoEncoderInfo::InitAsDefaultInstance() {
}

CarlifeVideoEncoderInfo::CarlifeVideoEncoderInfo(const CarlifeVideoEncoderInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeVideoEncoderInfo::SharedCtor() {
  _cached_size_ = 0;
  width_ = 0;
  height_ = 0;
  framerate_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeVideoEncoderInfo::~CarlifeVideoEncoderInfo() {
  SharedDtor();
}

void CarlifeVideoEncoderInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeVideoEncoderInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeVideoEncoderInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeVideoEncoderInfo_descriptor_;
}

const CarlifeVideoEncoderInfo& CarlifeVideoEncoderInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeVideoEncoderInfoProto_2eproto();
  return *default_instance_;
}

CarlifeVideoEncoderInfo* CarlifeVideoEncoderInfo::default_instance_ = NULL;

CarlifeVideoEncoderInfo* CarlifeVideoEncoderInfo::New() const {
  return new CarlifeVideoEncoderInfo;
}

void CarlifeVideoEncoderInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    width_ = 0;
    height_ = 0;
    framerate_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeVideoEncoderInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 width = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));
          set_has_width();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_height;
        break;
      }

      // required int32 height = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));
          set_has_height();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_frameRate;
        break;
      }

      // required int32 frameRate = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_frameRate:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &framerate_)));
          set_has_framerate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeVideoEncoderInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 width = 1;
  if (has_width()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->width(), output);
  }

  // required int32 height = 2;
  if (has_height()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->height(), output);
  }

  // required int32 frameRate = 3;
  if (has_framerate()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->framerate(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeVideoEncoderInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 width = 1;
  if (has_width()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->width(), target);
  }

  // required int32 height = 2;
  if (has_height()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->height(), target);
  }

  // required int32 frameRate = 3;
  if (has_framerate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->framerate(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeVideoEncoderInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 width = 1;
    if (has_width()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->width());
    }

    // required int32 height = 2;
    if (has_height()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->height());
    }

    // required int32 frameRate = 3;
    if (has_framerate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->framerate());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeVideoEncoderInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeVideoEncoderInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeVideoEncoderInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeVideoEncoderInfo::MergeFrom(const CarlifeVideoEncoderInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_width()) {
      set_width(from.width());
    }
    if (from.has_height()) {
      set_height(from.height());
    }
    if (from.has_framerate()) {
      set_framerate(from.framerate());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeVideoEncoderInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeVideoEncoderInfo::CopyFrom(const CarlifeVideoEncoderInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeVideoEncoderInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void CarlifeVideoEncoderInfo::Swap(CarlifeVideoEncoderInfo* other) {
  if (other != this) {
    std::swap(width_, other->width_);
    std::swap(height_, other->height_);
    std::swap(framerate_, other->framerate_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeVideoEncoderInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeVideoEncoderInfo_descriptor_;
  metadata.reflection = CarlifeVideoEncoderInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
