// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeConnectExceptionProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CarlifeConnectExceptionProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CarlifeConnectException_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CarlifeConnectException_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CarlifeConnectExceptionProto_2eproto() {
  protobuf_AddDesc_CarlifeConnectExceptionProto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CarlifeConnectExceptionProto.proto");
  GOOGLE_CHECK(file != NULL);
  CarlifeConnectException_descriptor_ = file->message_type(0);
  static const int CarlifeConnectException_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeConnectException, exceptiontype_),
  };
  CarlifeConnectException_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CarlifeConnectException_descriptor_,
      CarlifeConnectException::default_instance_,
      CarlifeConnectException_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeConnectException, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CarlifeConnectException, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CarlifeConnectException));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CarlifeConnectExceptionProto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CarlifeConnectException_descriptor_, &CarlifeConnectException::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CarlifeConnectExceptionProto_2eproto() {
  delete CarlifeConnectException::default_instance_;
  delete CarlifeConnectException_reflection_;
}

void protobuf_AddDesc_CarlifeConnectExceptionProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"CarlifeConnectExceptionProto.proto\022\032co"
    "m.baidu.carlife.protobuf\"0\n\027CarlifeConne"
    "ctException\022\025\n\rexceptionType\030\001 \002(\005", 114);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CarlifeConnectExceptionProto.proto", &protobuf_RegisterTypes);
  CarlifeConnectException::default_instance_ = new CarlifeConnectException();
  CarlifeConnectException::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CarlifeConnectExceptionProto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CarlifeConnectExceptionProto_2eproto {
  StaticDescriptorInitializer_CarlifeConnectExceptionProto_2eproto() {
    protobuf_AddDesc_CarlifeConnectExceptionProto_2eproto();
  }
} static_descriptor_initializer_CarlifeConnectExceptionProto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CarlifeConnectException::kExceptionTypeFieldNumber;
#endif  // !_MSC_VER

CarlifeConnectException::CarlifeConnectException()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CarlifeConnectException::InitAsDefaultInstance() {
}

CarlifeConnectException::CarlifeConnectException(const CarlifeConnectException& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CarlifeConnectException::SharedCtor() {
  _cached_size_ = 0;
  exceptiontype_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CarlifeConnectException::~CarlifeConnectException() {
  SharedDtor();
}

void CarlifeConnectException::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CarlifeConnectException::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CarlifeConnectException::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CarlifeConnectException_descriptor_;
}

const CarlifeConnectException& CarlifeConnectException::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CarlifeConnectExceptionProto_2eproto();
  return *default_instance_;
}

CarlifeConnectException* CarlifeConnectException::default_instance_ = NULL;

CarlifeConnectException* CarlifeConnectException::New() const {
  return new CarlifeConnectException;
}

void CarlifeConnectException::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    exceptiontype_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CarlifeConnectException::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 exceptionType = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &exceptiontype_)));
          set_has_exceptiontype();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CarlifeConnectException::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 exceptionType = 1;
  if (has_exceptiontype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->exceptiontype(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CarlifeConnectException::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 exceptionType = 1;
  if (has_exceptiontype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->exceptiontype(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CarlifeConnectException::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 exceptionType = 1;
    if (has_exceptiontype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->exceptiontype());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CarlifeConnectException::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CarlifeConnectException* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CarlifeConnectException*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CarlifeConnectException::MergeFrom(const CarlifeConnectException& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_exceptiontype()) {
      set_exceptiontype(from.exceptiontype());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CarlifeConnectException::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CarlifeConnectException::CopyFrom(const CarlifeConnectException& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CarlifeConnectException::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CarlifeConnectException::Swap(CarlifeConnectException* other) {
  if (other != this) {
    std::swap(exceptiontype_, other->exceptiontype_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CarlifeConnectException::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CarlifeConnectException_descriptor_;
  metadata.reflection = CarlifeConnectException_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

// @@protoc_insertion_point(global_scope)
