// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeFeatureConfigListProto.proto

#ifndef PROTOBUF_CarlifeFeatureConfigListProto_2eproto__INCLUDED
#define PROTOBUF_CarlifeFeatureConfigListProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "CarlifeFeatureConfigProto.pb.h"
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CarlifeFeatureConfigListProto_2eproto();
void protobuf_AssignDesc_CarlifeFeatureConfigListProto_2eproto();
void protobuf_ShutdownFile_CarlifeFeatureConfigListProto_2eproto();

class CarlifeFeatureConfigList;

// ===================================================================

class CarlifeFeatureConfigList : public ::google::protobuf::Message {
 public:
  CarlifeFeatureConfigList();
  virtual ~CarlifeFeatureConfigList();

  CarlifeFeatureConfigList(const CarlifeFeatureConfigList& from);

  inline CarlifeFeatureConfigList& operator=(const CarlifeFeatureConfigList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CarlifeFeatureConfigList& default_instance();

  void Swap(CarlifeFeatureConfigList* other);

  // implements Message ----------------------------------------------

  CarlifeFeatureConfigList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CarlifeFeatureConfigList& from);
  void MergeFrom(const CarlifeFeatureConfigList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 cnt = 1;
  inline bool has_cnt() const;
  inline void clear_cnt();
  static const int kCntFieldNumber = 1;
  inline ::google::protobuf::int32 cnt() const;
  inline void set_cnt(::google::protobuf::int32 value);

  // repeated .com.baidu.carlife.protobuf.CarlifeFeatureConfig featureConfig = 2;
  inline int featureconfig_size() const;
  inline void clear_featureconfig();
  static const int kFeatureConfigFieldNumber = 2;
  inline const ::com::baidu::carlife::protobuf::CarlifeFeatureConfig& featureconfig(int index) const;
  inline ::com::baidu::carlife::protobuf::CarlifeFeatureConfig* mutable_featureconfig(int index);
  inline ::com::baidu::carlife::protobuf::CarlifeFeatureConfig* add_featureconfig();
  inline const ::google::protobuf::RepeatedPtrField< ::com::baidu::carlife::protobuf::CarlifeFeatureConfig >&
      featureconfig() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::baidu::carlife::protobuf::CarlifeFeatureConfig >*
      mutable_featureconfig();

  // @@protoc_insertion_point(class_scope:com.baidu.carlife.protobuf.CarlifeFeatureConfigList)
 private:
  inline void set_has_cnt();
  inline void clear_has_cnt();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::com::baidu::carlife::protobuf::CarlifeFeatureConfig > featureconfig_;
  ::google::protobuf::int32 cnt_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_CarlifeFeatureConfigListProto_2eproto();
  friend void protobuf_AssignDesc_CarlifeFeatureConfigListProto_2eproto();
  friend void protobuf_ShutdownFile_CarlifeFeatureConfigListProto_2eproto();

  void InitAsDefaultInstance();
  static CarlifeFeatureConfigList* default_instance_;
};
// ===================================================================


// ===================================================================

// CarlifeFeatureConfigList

// required int32 cnt = 1;
inline bool CarlifeFeatureConfigList::has_cnt() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CarlifeFeatureConfigList::set_has_cnt() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CarlifeFeatureConfigList::clear_has_cnt() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CarlifeFeatureConfigList::clear_cnt() {
  cnt_ = 0;
  clear_has_cnt();
}
inline ::google::protobuf::int32 CarlifeFeatureConfigList::cnt() const {
  return cnt_;
}
inline void CarlifeFeatureConfigList::set_cnt(::google::protobuf::int32 value) {
  set_has_cnt();
  cnt_ = value;
}

// repeated .com.baidu.carlife.protobuf.CarlifeFeatureConfig featureConfig = 2;
inline int CarlifeFeatureConfigList::featureconfig_size() const {
  return featureconfig_.size();
}
inline void CarlifeFeatureConfigList::clear_featureconfig() {
  featureconfig_.Clear();
}
inline const ::com::baidu::carlife::protobuf::CarlifeFeatureConfig& CarlifeFeatureConfigList::featureconfig(int index) const {
  return featureconfig_.Get(index);
}
inline ::com::baidu::carlife::protobuf::CarlifeFeatureConfig* CarlifeFeatureConfigList::mutable_featureconfig(int index) {
  return featureconfig_.Mutable(index);
}
inline ::com::baidu::carlife::protobuf::CarlifeFeatureConfig* CarlifeFeatureConfigList::add_featureconfig() {
  return featureconfig_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::baidu::carlife::protobuf::CarlifeFeatureConfig >&
CarlifeFeatureConfigList::featureconfig() const {
  return featureconfig_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::baidu::carlife::protobuf::CarlifeFeatureConfig >*
CarlifeFeatureConfigList::mutable_featureconfig() {
  return &featureconfig_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CarlifeFeatureConfigListProto_2eproto__INCLUDED
