// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeFeatureConfigProto.proto

#ifndef PROTOBUF_CarlifeFeatureConfigProto_2eproto__INCLUDED
#define PROTOBUF_CarlifeFeatureConfigProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CarlifeFeatureConfigProto_2eproto();
void protobuf_AssignDesc_CarlifeFeatureConfigProto_2eproto();
void protobuf_ShutdownFile_CarlifeFeatureConfigProto_2eproto();

class CarlifeFeatureConfig;

// ===================================================================

class CarlifeFeatureConfig : public ::google::protobuf::Message {
 public:
  CarlifeFeatureConfig();
  virtual ~CarlifeFeatureConfig();

  CarlifeFeatureConfig(const CarlifeFeatureConfig& from);

  inline CarlifeFeatureConfig& operator=(const CarlifeFeatureConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CarlifeFeatureConfig& default_instance();

  void Swap(CarlifeFeatureConfig* other);

  // implements Message ----------------------------------------------

  CarlifeFeatureConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CarlifeFeatureConfig& from);
  void MergeFrom(const CarlifeFeatureConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 1;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const char* value, size_t size);
  inline ::std::string* mutable_key();
  inline ::std::string* release_key();
  inline void set_allocated_key(::std::string* key);

  // required int32 value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline ::google::protobuf::int32 value() const;
  inline void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.baidu.carlife.protobuf.CarlifeFeatureConfig)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* key_;
  ::google::protobuf::int32 value_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_CarlifeFeatureConfigProto_2eproto();
  friend void protobuf_AssignDesc_CarlifeFeatureConfigProto_2eproto();
  friend void protobuf_ShutdownFile_CarlifeFeatureConfigProto_2eproto();

  void InitAsDefaultInstance();
  static CarlifeFeatureConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// CarlifeFeatureConfig

// required string key = 1;
inline bool CarlifeFeatureConfig::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CarlifeFeatureConfig::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CarlifeFeatureConfig::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CarlifeFeatureConfig::clear_key() {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& CarlifeFeatureConfig::key() const {
  return *key_;
}
inline void CarlifeFeatureConfig::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void CarlifeFeatureConfig::set_key(const char* value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void CarlifeFeatureConfig::set_key(const char* value, size_t size) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CarlifeFeatureConfig::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  return key_;
}
inline ::std::string* CarlifeFeatureConfig::release_key() {
  clear_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CarlifeFeatureConfig::set_allocated_key(::std::string* key) {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    delete key_;
  }
  if (key) {
    set_has_key();
    key_ = key;
  } else {
    clear_has_key();
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 value = 2;
inline bool CarlifeFeatureConfig::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CarlifeFeatureConfig::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CarlifeFeatureConfig::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CarlifeFeatureConfig::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline ::google::protobuf::int32 CarlifeFeatureConfig::value() const {
  return value_;
}
inline void CarlifeFeatureConfig::set_value(::google::protobuf::int32 value) {
  set_has_value();
  value_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CarlifeFeatureConfigProto_2eproto__INCLUDED
