// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeNaviAssitantGuideInfoProto.proto

#ifndef PROTOBUF_CarlifeNaviAssitantGuideInfoProto_2eproto__INCLUDED
#define PROTOBUF_CarlifeNaviAssitantGuideInfoProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CarlifeNaviAssitantGuideInfoProto_2eproto();
void protobuf_AssignDesc_CarlifeNaviAssitantGuideInfoProto_2eproto();
void protobuf_ShutdownFile_CarlifeNaviAssitantGuideInfoProto_2eproto();

class CarlifeNaviAssitantGuideInfo;

// ===================================================================

class CarlifeNaviAssitantGuideInfo : public ::google::protobuf::Message {
 public:
  CarlifeNaviAssitantGuideInfo();
  virtual ~CarlifeNaviAssitantGuideInfo();

  CarlifeNaviAssitantGuideInfo(const CarlifeNaviAssitantGuideInfo& from);

  inline CarlifeNaviAssitantGuideInfo& operator=(const CarlifeNaviAssitantGuideInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CarlifeNaviAssitantGuideInfo& default_instance();

  void Swap(CarlifeNaviAssitantGuideInfo* other);

  // implements Message ----------------------------------------------

  CarlifeNaviAssitantGuideInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CarlifeNaviAssitantGuideInfo& from);
  void MergeFrom(const CarlifeNaviAssitantGuideInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 action = 1;
  inline bool has_action() const;
  inline void clear_action();
  static const int kActionFieldNumber = 1;
  inline ::google::protobuf::int32 action() const;
  inline void set_action(::google::protobuf::int32 value);

  // required int32 assistantType = 2;
  inline bool has_assistanttype() const;
  inline void clear_assistanttype();
  static const int kAssistantTypeFieldNumber = 2;
  inline ::google::protobuf::int32 assistanttype() const;
  inline void set_assistanttype(::google::protobuf::int32 value);

  // required int32 trafficSignType = 3;
  inline bool has_trafficsigntype() const;
  inline void clear_trafficsigntype();
  static const int kTrafficSignTypeFieldNumber = 3;
  inline ::google::protobuf::int32 trafficsigntype() const;
  inline void set_trafficsigntype(::google::protobuf::int32 value);

  // required int32 totalDistance = 4;
  inline bool has_totaldistance() const;
  inline void clear_totaldistance();
  static const int kTotalDistanceFieldNumber = 4;
  inline ::google::protobuf::int32 totaldistance() const;
  inline void set_totaldistance(::google::protobuf::int32 value);

  // required int32 remainDistance = 5;
  inline bool has_remaindistance() const;
  inline void clear_remaindistance();
  static const int kRemainDistanceFieldNumber = 5;
  inline ::google::protobuf::int32 remaindistance() const;
  inline void set_remaindistance(::google::protobuf::int32 value);

  // required int32 cameraSpeed = 6;
  inline bool has_cameraspeed() const;
  inline void clear_cameraspeed();
  static const int kCameraSpeedFieldNumber = 6;
  inline ::google::protobuf::int32 cameraspeed() const;
  inline void set_cameraspeed(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.baidu.carlife.protobuf.CarlifeNaviAssitantGuideInfo)
 private:
  inline void set_has_action();
  inline void clear_has_action();
  inline void set_has_assistanttype();
  inline void clear_has_assistanttype();
  inline void set_has_trafficsigntype();
  inline void clear_has_trafficsigntype();
  inline void set_has_totaldistance();
  inline void clear_has_totaldistance();
  inline void set_has_remaindistance();
  inline void clear_has_remaindistance();
  inline void set_has_cameraspeed();
  inline void clear_has_cameraspeed();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 action_;
  ::google::protobuf::int32 assistanttype_;
  ::google::protobuf::int32 trafficsigntype_;
  ::google::protobuf::int32 totaldistance_;
  ::google::protobuf::int32 remaindistance_;
  ::google::protobuf::int32 cameraspeed_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_CarlifeNaviAssitantGuideInfoProto_2eproto();
  friend void protobuf_AssignDesc_CarlifeNaviAssitantGuideInfoProto_2eproto();
  friend void protobuf_ShutdownFile_CarlifeNaviAssitantGuideInfoProto_2eproto();

  void InitAsDefaultInstance();
  static CarlifeNaviAssitantGuideInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// CarlifeNaviAssitantGuideInfo

// required int32 action = 1;
inline bool CarlifeNaviAssitantGuideInfo::has_action() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CarlifeNaviAssitantGuideInfo::set_has_action() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_has_action() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_action() {
  action_ = 0;
  clear_has_action();
}
inline ::google::protobuf::int32 CarlifeNaviAssitantGuideInfo::action() const {
  return action_;
}
inline void CarlifeNaviAssitantGuideInfo::set_action(::google::protobuf::int32 value) {
  set_has_action();
  action_ = value;
}

// required int32 assistantType = 2;
inline bool CarlifeNaviAssitantGuideInfo::has_assistanttype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CarlifeNaviAssitantGuideInfo::set_has_assistanttype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_has_assistanttype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_assistanttype() {
  assistanttype_ = 0;
  clear_has_assistanttype();
}
inline ::google::protobuf::int32 CarlifeNaviAssitantGuideInfo::assistanttype() const {
  return assistanttype_;
}
inline void CarlifeNaviAssitantGuideInfo::set_assistanttype(::google::protobuf::int32 value) {
  set_has_assistanttype();
  assistanttype_ = value;
}

// required int32 trafficSignType = 3;
inline bool CarlifeNaviAssitantGuideInfo::has_trafficsigntype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CarlifeNaviAssitantGuideInfo::set_has_trafficsigntype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_has_trafficsigntype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_trafficsigntype() {
  trafficsigntype_ = 0;
  clear_has_trafficsigntype();
}
inline ::google::protobuf::int32 CarlifeNaviAssitantGuideInfo::trafficsigntype() const {
  return trafficsigntype_;
}
inline void CarlifeNaviAssitantGuideInfo::set_trafficsigntype(::google::protobuf::int32 value) {
  set_has_trafficsigntype();
  trafficsigntype_ = value;
}

// required int32 totalDistance = 4;
inline bool CarlifeNaviAssitantGuideInfo::has_totaldistance() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CarlifeNaviAssitantGuideInfo::set_has_totaldistance() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_has_totaldistance() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_totaldistance() {
  totaldistance_ = 0;
  clear_has_totaldistance();
}
inline ::google::protobuf::int32 CarlifeNaviAssitantGuideInfo::totaldistance() const {
  return totaldistance_;
}
inline void CarlifeNaviAssitantGuideInfo::set_totaldistance(::google::protobuf::int32 value) {
  set_has_totaldistance();
  totaldistance_ = value;
}

// required int32 remainDistance = 5;
inline bool CarlifeNaviAssitantGuideInfo::has_remaindistance() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CarlifeNaviAssitantGuideInfo::set_has_remaindistance() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_has_remaindistance() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_remaindistance() {
  remaindistance_ = 0;
  clear_has_remaindistance();
}
inline ::google::protobuf::int32 CarlifeNaviAssitantGuideInfo::remaindistance() const {
  return remaindistance_;
}
inline void CarlifeNaviAssitantGuideInfo::set_remaindistance(::google::protobuf::int32 value) {
  set_has_remaindistance();
  remaindistance_ = value;
}

// required int32 cameraSpeed = 6;
inline bool CarlifeNaviAssitantGuideInfo::has_cameraspeed() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CarlifeNaviAssitantGuideInfo::set_has_cameraspeed() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_has_cameraspeed() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CarlifeNaviAssitantGuideInfo::clear_cameraspeed() {
  cameraspeed_ = 0;
  clear_has_cameraspeed();
}
inline ::google::protobuf::int32 CarlifeNaviAssitantGuideInfo::cameraspeed() const {
  return cameraspeed_;
}
inline void CarlifeNaviAssitantGuideInfo::set_cameraspeed(::google::protobuf::int32 value) {
  set_has_cameraspeed();
  cameraspeed_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CarlifeNaviAssitantGuideInfoProto_2eproto__INCLUDED
