// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeBTHfpStatusResponseProto.proto

#ifndef PROTOBUF_CarlifeBTHfpStatusResponseProto_2eproto__INCLUDED
#define PROTOBUF_CarlifeBTHfpStatusResponseProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CarlifeBTHfpStatusResponseProto_2eproto();
void protobuf_AssignDesc_CarlifeBTHfpStatusResponseProto_2eproto();
void protobuf_ShutdownFile_CarlifeBTHfpStatusResponseProto_2eproto();

class CarlifeBTHfpStatusResponse;

// ===================================================================

class CarlifeBTHfpStatusResponse : public ::google::protobuf::Message {
 public:
  CarlifeBTHfpStatusResponse();
  virtual ~CarlifeBTHfpStatusResponse();

  CarlifeBTHfpStatusResponse(const CarlifeBTHfpStatusResponse& from);

  inline CarlifeBTHfpStatusResponse& operator=(const CarlifeBTHfpStatusResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CarlifeBTHfpStatusResponse& default_instance();

  void Swap(CarlifeBTHfpStatusResponse* other);

  // implements Message ----------------------------------------------

  CarlifeBTHfpStatusResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CarlifeBTHfpStatusResponse& from);
  void MergeFrom(const CarlifeBTHfpStatusResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // required int32 type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.baidu.carlife.protobuf.CarlifeBTHfpStatusResponse)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_CarlifeBTHfpStatusResponseProto_2eproto();
  friend void protobuf_AssignDesc_CarlifeBTHfpStatusResponseProto_2eproto();
  friend void protobuf_ShutdownFile_CarlifeBTHfpStatusResponseProto_2eproto();

  void InitAsDefaultInstance();
  static CarlifeBTHfpStatusResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// CarlifeBTHfpStatusResponse

// required int32 status = 1;
inline bool CarlifeBTHfpStatusResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CarlifeBTHfpStatusResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CarlifeBTHfpStatusResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CarlifeBTHfpStatusResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 CarlifeBTHfpStatusResponse::status() const {
  return status_;
}
inline void CarlifeBTHfpStatusResponse::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
}

// required int32 type = 2;
inline bool CarlifeBTHfpStatusResponse::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CarlifeBTHfpStatusResponse::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CarlifeBTHfpStatusResponse::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CarlifeBTHfpStatusResponse::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 CarlifeBTHfpStatusResponse::type() const {
  return type_;
}
inline void CarlifeBTHfpStatusResponse::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CarlifeBTHfpStatusResponseProto_2eproto__INCLUDED
