// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeMusicInitProto.proto

#ifndef PROTOBUF_CarlifeMusicInitProto_2eproto__INCLUDED
#define PROTOBUF_CarlifeMusicInitProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CarlifeMusicInitProto_2eproto();
void protobuf_AssignDesc_CarlifeMusicInitProto_2eproto();
void protobuf_ShutdownFile_CarlifeMusicInitProto_2eproto();

class CarlifeMusicInit;

// ===================================================================

class CarlifeMusicInit : public ::google::protobuf::Message {
 public:
  CarlifeMusicInit();
  virtual ~CarlifeMusicInit();

  CarlifeMusicInit(const CarlifeMusicInit& from);

  inline CarlifeMusicInit& operator=(const CarlifeMusicInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CarlifeMusicInit& default_instance();

  void Swap(CarlifeMusicInit* other);

  // implements Message ----------------------------------------------

  CarlifeMusicInit* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CarlifeMusicInit& from);
  void MergeFrom(const CarlifeMusicInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 sampleRate = 1;
  inline bool has_samplerate() const;
  inline void clear_samplerate();
  static const int kSampleRateFieldNumber = 1;
  inline ::google::protobuf::int32 samplerate() const;
  inline void set_samplerate(::google::protobuf::int32 value);

  // required int32 channelConfig = 2;
  inline bool has_channelconfig() const;
  inline void clear_channelconfig();
  static const int kChannelConfigFieldNumber = 2;
  inline ::google::protobuf::int32 channelconfig() const;
  inline void set_channelconfig(::google::protobuf::int32 value);

  // required int32 sampleFormat = 3;
  inline bool has_sampleformat() const;
  inline void clear_sampleformat();
  static const int kSampleFormatFieldNumber = 3;
  inline ::google::protobuf::int32 sampleformat() const;
  inline void set_sampleformat(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.baidu.carlife.protobuf.CarlifeMusicInit)
 private:
  inline void set_has_samplerate();
  inline void clear_has_samplerate();
  inline void set_has_channelconfig();
  inline void clear_has_channelconfig();
  inline void set_has_sampleformat();
  inline void clear_has_sampleformat();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 samplerate_;
  ::google::protobuf::int32 channelconfig_;
  ::google::protobuf::int32 sampleformat_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_CarlifeMusicInitProto_2eproto();
  friend void protobuf_AssignDesc_CarlifeMusicInitProto_2eproto();
  friend void protobuf_ShutdownFile_CarlifeMusicInitProto_2eproto();

  void InitAsDefaultInstance();
  static CarlifeMusicInit* default_instance_;
};
// ===================================================================


// ===================================================================

// CarlifeMusicInit

// required int32 sampleRate = 1;
inline bool CarlifeMusicInit::has_samplerate() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CarlifeMusicInit::set_has_samplerate() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CarlifeMusicInit::clear_has_samplerate() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CarlifeMusicInit::clear_samplerate() {
  samplerate_ = 0;
  clear_has_samplerate();
}
inline ::google::protobuf::int32 CarlifeMusicInit::samplerate() const {
  return samplerate_;
}
inline void CarlifeMusicInit::set_samplerate(::google::protobuf::int32 value) {
  set_has_samplerate();
  samplerate_ = value;
}

// required int32 channelConfig = 2;
inline bool CarlifeMusicInit::has_channelconfig() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CarlifeMusicInit::set_has_channelconfig() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CarlifeMusicInit::clear_has_channelconfig() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CarlifeMusicInit::clear_channelconfig() {
  channelconfig_ = 0;
  clear_has_channelconfig();
}
inline ::google::protobuf::int32 CarlifeMusicInit::channelconfig() const {
  return channelconfig_;
}
inline void CarlifeMusicInit::set_channelconfig(::google::protobuf::int32 value) {
  set_has_channelconfig();
  channelconfig_ = value;
}

// required int32 sampleFormat = 3;
inline bool CarlifeMusicInit::has_sampleformat() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CarlifeMusicInit::set_has_sampleformat() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CarlifeMusicInit::clear_has_sampleformat() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CarlifeMusicInit::clear_sampleformat() {
  sampleformat_ = 0;
  clear_has_sampleformat();
}
inline ::google::protobuf::int32 CarlifeMusicInit::sampleformat() const {
  return sampleformat_;
}
inline void CarlifeMusicInit::set_sampleformat(::google::protobuf::int32 value) {
  set_has_sampleformat();
  sampleformat_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CarlifeMusicInitProto_2eproto__INCLUDED
