// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeCarHardKeyCodeProto.proto

#ifndef PROTOBUF_CarlifeCarHardKeyCodeProto_2eproto__INCLUDED
#define PROTOBUF_CarlifeCarHardKeyCodeProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CarlifeCarHardKeyCodeProto_2eproto();
void protobuf_AssignDesc_CarlifeCarHardKeyCodeProto_2eproto();
void protobuf_ShutdownFile_CarlifeCarHardKeyCodeProto_2eproto();

class CarlifeCarHardKeyCode;

// ===================================================================

class CarlifeCarHardKeyCode : public ::google::protobuf::Message {
 public:
  CarlifeCarHardKeyCode();
  virtual ~CarlifeCarHardKeyCode();

  CarlifeCarHardKeyCode(const CarlifeCarHardKeyCode& from);

  inline CarlifeCarHardKeyCode& operator=(const CarlifeCarHardKeyCode& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CarlifeCarHardKeyCode& default_instance();

  void Swap(CarlifeCarHardKeyCode* other);

  // implements Message ----------------------------------------------

  CarlifeCarHardKeyCode* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CarlifeCarHardKeyCode& from);
  void MergeFrom(const CarlifeCarHardKeyCode& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 keycode = 1;
  inline bool has_keycode() const;
  inline void clear_keycode();
  static const int kKeycodeFieldNumber = 1;
  inline ::google::protobuf::int32 keycode() const;
  inline void set_keycode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.baidu.carlife.protobuf.CarlifeCarHardKeyCode)
 private:
  inline void set_has_keycode();
  inline void clear_has_keycode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 keycode_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_CarlifeCarHardKeyCodeProto_2eproto();
  friend void protobuf_AssignDesc_CarlifeCarHardKeyCodeProto_2eproto();
  friend void protobuf_ShutdownFile_CarlifeCarHardKeyCodeProto_2eproto();

  void InitAsDefaultInstance();
  static CarlifeCarHardKeyCode* default_instance_;
};
// ===================================================================


// ===================================================================

// CarlifeCarHardKeyCode

// required int32 keycode = 1;
inline bool CarlifeCarHardKeyCode::has_keycode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CarlifeCarHardKeyCode::set_has_keycode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CarlifeCarHardKeyCode::clear_has_keycode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CarlifeCarHardKeyCode::clear_keycode() {
  keycode_ = 0;
  clear_has_keycode();
}
inline ::google::protobuf::int32 CarlifeCarHardKeyCode::keycode() const {
  return keycode_;
}
inline void CarlifeCarHardKeyCode::set_keycode(::google::protobuf::int32 value) {
  set_has_keycode();
  keycode_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CarlifeCarHardKeyCodeProto_2eproto__INCLUDED
