// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarlifeVehicleInfoProto.proto

#ifndef PROTOBUF_CarlifeVehicleInfoProto_2eproto__INCLUDED
#define PROTOBUF_CarlifeVehicleInfoProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace baidu {
namespace carlife {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CarlifeVehicleInfoProto_2eproto();
void protobuf_AssignDesc_CarlifeVehicleInfoProto_2eproto();
void protobuf_ShutdownFile_CarlifeVehicleInfoProto_2eproto();

class CarlifeVehicleInfo;

// ===================================================================

class CarlifeVehicleInfo : public ::google::protobuf::Message {
 public:
  CarlifeVehicleInfo();
  virtual ~CarlifeVehicleInfo();

  CarlifeVehicleInfo(const CarlifeVehicleInfo& from);

  inline CarlifeVehicleInfo& operator=(const CarlifeVehicleInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CarlifeVehicleInfo& default_instance();

  void Swap(CarlifeVehicleInfo* other);

  // implements Message ----------------------------------------------

  CarlifeVehicleInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CarlifeVehicleInfo& from);
  void MergeFrom(const CarlifeVehicleInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 moduleID = 1;
  inline bool has_moduleid() const;
  inline void clear_moduleid();
  static const int kModuleIDFieldNumber = 1;
  inline ::google::protobuf::int32 moduleid() const;
  inline void set_moduleid(::google::protobuf::int32 value);

  // optional bool supportFlag = 2;
  inline bool has_supportflag() const;
  inline void clear_supportflag();
  static const int kSupportFlagFieldNumber = 2;
  inline bool supportflag() const;
  inline void set_supportflag(bool value);

  // optional int32 frequency = 3;
  inline bool has_frequency() const;
  inline void clear_frequency();
  static const int kFrequencyFieldNumber = 3;
  inline ::google::protobuf::int32 frequency() const;
  inline void set_frequency(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.baidu.carlife.protobuf.CarlifeVehicleInfo)
 private:
  inline void set_has_moduleid();
  inline void clear_has_moduleid();
  inline void set_has_supportflag();
  inline void clear_has_supportflag();
  inline void set_has_frequency();
  inline void clear_has_frequency();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 moduleid_;
  bool supportflag_;
  ::google::protobuf::int32 frequency_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_CarlifeVehicleInfoProto_2eproto();
  friend void protobuf_AssignDesc_CarlifeVehicleInfoProto_2eproto();
  friend void protobuf_ShutdownFile_CarlifeVehicleInfoProto_2eproto();

  void InitAsDefaultInstance();
  static CarlifeVehicleInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// CarlifeVehicleInfo

// required int32 moduleID = 1;
inline bool CarlifeVehicleInfo::has_moduleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CarlifeVehicleInfo::set_has_moduleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CarlifeVehicleInfo::clear_has_moduleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CarlifeVehicleInfo::clear_moduleid() {
  moduleid_ = 0;
  clear_has_moduleid();
}
inline ::google::protobuf::int32 CarlifeVehicleInfo::moduleid() const {
  return moduleid_;
}
inline void CarlifeVehicleInfo::set_moduleid(::google::protobuf::int32 value) {
  set_has_moduleid();
  moduleid_ = value;
}

// optional bool supportFlag = 2;
inline bool CarlifeVehicleInfo::has_supportflag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CarlifeVehicleInfo::set_has_supportflag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CarlifeVehicleInfo::clear_has_supportflag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CarlifeVehicleInfo::clear_supportflag() {
  supportflag_ = false;
  clear_has_supportflag();
}
inline bool CarlifeVehicleInfo::supportflag() const {
  return supportflag_;
}
inline void CarlifeVehicleInfo::set_supportflag(bool value) {
  set_has_supportflag();
  supportflag_ = value;
}

// optional int32 frequency = 3;
inline bool CarlifeVehicleInfo::has_frequency() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CarlifeVehicleInfo::set_has_frequency() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CarlifeVehicleInfo::clear_has_frequency() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CarlifeVehicleInfo::clear_frequency() {
  frequency_ = 0;
  clear_has_frequency();
}
inline ::google::protobuf::int32 CarlifeVehicleInfo::frequency() const {
  return frequency_;
}
inline void CarlifeVehicleInfo::set_frequency(::google::protobuf::int32 value) {
  set_has_frequency();
  frequency_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace carlife
}  // namespace baidu
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CarlifeVehicleInfoProto_2eproto__INCLUDED
